Map<String, String> Bangla = {
  // -------------------- App Info --------------------
  'version': 'সংস্করণ',
  'App_Version': 'অ্যাপ সংস্করণ',

  // --------------------  Login --------------------
  'Login_Headline': 'বিক্রেতা-তে স্বাগতম',
  'Sign_in_bottom_text_1': "কোন অ্যাকাউন্ট নেই? ",
  'Sign_in_bottom_text_2': 'সাইন আপ করুন',
  'Forgot_password': 'পাসওয়ার্ড ভুলে গেছেন',
  'Please_enter_email_address_to_reset_the_password':
      'পাসওয়ার্ড রিসেট করার জন্য অনুগ্রহ করে ইমেইল অ্যাড্রেস লিখুন',
  'Login_Button': 'লগইন করুন',
  'BackTo_login': 'লগইনে ফিরে যান',
  'Please_enter_an_email_address': 'দয়া করে একটি ইমেইল ঠিকানা লিখুন',
  'Please_enter_a_valid_email_address': 'দয়া করে একটি বৈধ ইমেইল ঠিকানা লিখুন',
  'Please_enter_Password': 'দয়া করে পাসওয়ার্ড লিখুন',
  'Password_hints':
      'পাসওয়ার্ডে অবশ্যই ৮+ অক্ষর, বড় হাতের, ছোট হাতের এবং বিশেষ অক্ষর থাকতে হবে',
  'No_account_found': 'কোন অ্যাকাউন্ট পাওয়া যায়নি',
  'Login_successful!': 'লগইন সফল হয়েছে!',
  'user_not_found': 'ব্যবহারকারী খুঁজে পাওয়া যায়নি',
  'No_account_found_for_that_email':
      'এই ইমেলের জন্য কোনো অ্যাকাউন্ট পাওয়া যায়নি।',
  'wrong_password': 'ভুল পাসওয়ার্ড',
  'Incorrect_password_Please_try_again.':
      'ভুল পাসওয়ার্ড। অনুগ্রহ করে আবার চেষ্টা করুন।',
  'invalid_email.': 'অবৈধ ইমেইল।',
  'The_email_address_is_not_valid..': 'ইমেইল ঠিকানাটি বৈধ নয়।',
  'Login_failed_Please_try_again':
      'লগইন ব্যর্থ হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।',
  'Password_Reset_Link_sent_successfully_Check_your_email':
      'পাসওয়ার্ড রিসেট লিঙ্ক পাঠানো হয়েছে! ইমেইল চেক করুন',
  'Too_many_requests_Please_try_again_later.':
      'অনেক বেশি অনুরোধ করা হয়েছে। দয়া করে পরে আবার চেষ্টা করুন।',
  'Account_already_exists_with_this_email':
      'এই ইমেইল দিয়ে ইতিমধ্যেই একটি অ্যাকাউন্ট আছে।',

  // -------------------- SignUp --------------------
  'SignUp_Headline': 'অ্যাকাউন্ট তৈরি করুন',
  'SignUp_subHeadLine': "আমরা আপনার ইমেইল ঠিকানায় একটি (OTP) পাঠাব",
  'Sign_up_bottom_text_1': 'একটি অ্যাকাউন্ট আছে? ',
  'Sign_up_bottom_text_2': ' সাইন ইন করুন',
  'SignUp_Button': 'সাইন আপ করুন',
  'Shop_HeadLine': 'দোকানের তথ্য',
  'Email': 'ইমেইল',
  'Password': 'পাসওয়ার্ড',
  'Confirm_Password': 'পাসওয়ার্ড নিশ্চিত করুন',
  'First_Name': 'প্রথম নাম',
  'Last_Name': 'শেষ নাম',
  'Phone_Number': 'ফোন নম্বর',
  'Shop_Name': 'দোকানের নাম',
  'Address': 'ঠিকানা',
  'Select_shop_type': 'দোকানের ধরন নির্বাচন করুন',
  'Shop_name_is_required': 'দোকানের নাম আবশ্যক',
  'Please_enter_phone_number': 'দয়া করে ফোন নম্বর লিখুন',
  'Please_enter_a_valid_phone_number': 'দয়া করে একটি বৈধ ফোন নম্বর লিখুন',
  'Please_select_shop_type': 'দয়া করে দোকানের ধরন নির্বাচন করুন',
  'Passwords_do_not_match': 'পাসওয়ার্ড মেলে না',
  'Sign_Up_Successful': 'সাইন আপ সফল!',
  'Your_password_is_too_weak_Please_use_at.....':
      'আপনার পাসওয়ার্ড খুব দুর্বল। অনুগ্রহ করে কমপক্ষে ৬টি অক্ষর ব্যবহার করুন।',
  'This_email_is_already_registered':
      'এই ইমেইলটি ইতিমধ্যেই নিবন্ধিত। সাইন ইন করার চেষ্টা করুন।',
  'Something_went_wrong': 'কিছু ভুল হয়েছে। দয়া করে আবার চেষ্টা করুন।',

  // -------------------- OTP --------------------
  'OTP_Headline': 'ওটিপি যাচাইকরণ',
  'OTP_subHeadLine': 'আপনার ইমেইল ঠিকানায় পাঠানো (OTP) কোডটি লিখুন',
  'Didnt_receive_a_code': "কোড পাননি?",
  'Resend': 'পুনরায় পাঠান',
  'OTP_Button': 'যাচাই করুন',
  'OTP_Verified_Successfully': 'ওটিপি সফলভাবে যাচাই হয়েছে',
  'Invalid_OTP_Please_try_again': 'অবৈধ ওটিপি! দয়া করে আবার চেষ্টা করুন',

  // -------------------- Settings --------------------
  'Settings': 'সেটিংস',
  'Account': 'অ্যাকাউন্ট',
  'Profile': 'প্রোফাইল',
  'Name_phone_address': 'নাম, ফোন, ঠিকানা',
  'Notifications': 'নোটিফিকেশন',
  'Push_Notifications': 'পুশ নোটিফিকেশন',
  'Enable_all_notifications': 'সব নোটিফিকেশন চালু করুন',
  'Expire_date_Alerts': 'মেয়াদ উত্তীর্ণের সতর্কবার্তা',
  'Get_notified_before_items_expire':
      'পণ্য মেয়াদ উত্তীর্ণের আগে নোটিফিকেশন পান',
  'Low_Stock_Alerts': 'কম স্টক সতর্কতা',
  'Get_notified_when_stock_is_low': 'স্টক কম হলে নোটিফিকেশন পান',
  'Security': 'নিরাপত্তা',
  'Change_Password': 'পাসওয়ার্ড পরিবর্তন করুন',
  'Update_your_account_password': 'আপনার অ্যাকাউন্টের পাসওয়ার্ড আপডেট করুন',
  'Language_Theme': 'ভাষা ও থিম',
  'Language': 'ভাষা',
  'Theme': 'থিম',
  'Dark_mode_is_active': 'ডার্ক মোড সক্রিয় আছে',
  'Light_mode_is_active': 'লাইট মোড সক্রিয় আছে',
  'About_Help': 'সম্পর্কে ও সহায়তা',
  'Support_FAQs': 'সহায়তা ও প্রায়শই জিজ্ঞাসিত প্রশ্নাবলী',
  'Get_help_or_contact_support': 'সহায়তা পান বা সাপোর্টে যোগাযোগ করুন',
  'About_Us': 'আমাদের সম্পর্কে',
  'Learn_more_about_Bikretaa': 'বিক্রেতা সম্পর্কে আরও জানুন',

  // Danger Zone / Account Controls
  'DANGER_ZONE': 'অ্যাকাউন্ট নিয়ন্ত্রণ',
  'Log_out': 'লগ আউট',
  'Logout': 'লগ আউট',
  'Reset_Password': 'পাসওয়ার্ড রিসেট করুন',
  'Send': 'পাঠান',
  'Are_you_sure_you_want_to_Logout': 'আপনি কি নিশ্চিত যে লগ আউট করতে চান?',
  'Reset_Password_Message': 'আপনি কি একটি পাসওয়ার্ড রিসেট লিঙ্ক পাঠাতে চান?',
  'Password_Reset_Success': 'পাসওয়ার্ড রিসেট লিঙ্ক পাঠানো হয়েছে',

  // -------------------- Profile --------------------
  'update_profile': 'প্রোফাইল হালনাগাদ',
  'update_profile_btn': 'প্রোফাইল হালনাগাদ করুন',
  'user_data_not_found': 'ত্রুটি: ব্যবহারকারীর তথ্য পাওয়া যায়নি',
  'profile_updated_success': 'প্রোফাইল সফলভাবে আপডেট হয়েছে!',
  'error_updating_profile': 'প্রোফাইল আপডেট করতে সমস্যা হয়েছে',
  'profile': 'প্রোফাইল',
  'error_loading_user': 'ব্যবহারকারীর তথ্য লোড করতে সমস্যা হয়েছে',
  'no_user_data': 'কোনো ব্যবহারকারীর তথ্য পাওয়া যায়নি',
  'contact_information': 'যোগাযোগের তথ্য',
  'edit_profile': 'প্রোফাইল সম্পাদনা করুন',
  'change_password': 'পাসওয়ার্ড পরিবর্তন করুন',
  'Edit': 'সম্পাদনা করুন',

  // -------------------- About Bikretaa --------------------
  'about_bikretaa': 'বিক্রেতা সম্পর্কে',
  'bikretaa_description':
      'বিক্রেতা হলো একটি আধুনিক শপ ম্যানেজমেন্ট অ্যাপ। এটি দোকানদারদের জন্য ডিজাইন করা হয়েছে যাতে তারা সহজে প্রোডাক্ট যোগ করতে পারে, স্টক এবং মেয়াদ শেষের তারিখ ট্র্যাক করতে পারে, বকেয়া পেমেন্ট পরিচালনা করতে পারে এবং বিস্তারিত বিক্রয় রিপোর্ট দেখতে পারে।',
  'why_bikretaa': 'কেন বিক্রেতা?',
  'fast_product_management': 'দ্রুত প্রোডাক্ট ব্যবস্থাপনা',
  'stock_and_expiry_tracking': 'স্টক এবং মেয়াদ শেষের তারিখ ট্র্যাকিং',
  'low_stock_alerts': 'কম স্টক এবং মেয়াদ শেষের সতর্কতা',
  'sales_reports': 'বিক্রয় রিপোর্ট ও বিশ্লেষণ',
  'secure_login': 'নিরাপদ লগইন ও অ্যাকাউন্ট ম্যানেজমেন্ট',
  'developed_by': 'উন্নয়ন করেছেন:',
  'footer_text': '© ২০২৫ বিক্রেতা টিম। সর্বস্বত্ব সংরক্ষিত।',

  // -------------------- FAQs / Support --------------------
  'support_faqs': 'সাপোর্ট ও FAQ',
  'support_welcome':
      'বিক্রেতা সাপোর্টে স্বাগতম! এখানে আপনি প্রায়শই জিজ্ঞাসিত প্রশ্নের উত্তর এবং অ্যাপ ব্যবহার সম্পর্কিত নির্দেশিকা পাবেন।',
  'faq_manage_products_title': 'কিভাবে প্রোডাক্ট ম্যানেজ করবেন?',
  'faq_manage_products_desc':
      'প্রোডাক্ট স্ক্রিনে যান এবং "Add Product" চাপুন নতুন আইটেম যোগ করতে। আপনি ক্রয় মূল্য, বিক্রয় মূল্য, স্টক পরিমাণ, মেয়াদ শেষের তারিখ এবং ডিসকাউন্ট সেট করতে পারেন। সমস্ত যোগকৃত প্রোডাক্ট প্রোডাক্ট স্ক্রিনে দেখাবে।',
  'faq_track_sales_title': 'কিভাবে বিক্রয় ট্র্যাক করবেন?',
  'faq_track_sales_desc':
      'প্রতিটি বিক্রয় স্বয়ংক্রিয়ভাবে বিক্রয় সেকশনে রেকর্ড হয়। আপনি দৈনিক, সাপ্তাহিক এবং মাসিক রিপোর্ট গ্রাফিক্যাল চার্টের মাধ্যমে দেখতে পারেন।',
  'faq_stock_alerts_title': 'কম স্টক এবং মেয়াদ শেষের সতর্কতা কিভাবে পাবেন?',
  'faq_stock_alerts_desc':
      'সেটিংস পেজ থেকে নোটিফিকেশন সক্রিয় করুন। স্টক কম বা প্রোডাক্টের মেয়াদ শেষের সময় অ্যাপ সতর্ক করবে।',
  'faq_reset_password_title': 'কিভাবে পাসওয়ার্ড রিসেট করবেন?',
  'faq_reset_password_desc':
      'Settings > Security > Change Password যান। আপনার রেজিস্টার করা ইমেইলে একটি পাসওয়ার্ড রিসেট লিংক পাঠানো হবে।',

  // -------------------- Account Deletion --------------------
  'account_deletion': 'অ্যাকাউন্ট মুছুন',
  'account_deletion_warning': 'আপনার অ্যাকাউন্ট মুছলে নিম্নলিখিত ফলাফল ঘটবে:',
  'account_deletion_desc':
      'আপনার ব্যক্তিগত তথ্য স্থায়ীভাবে মুছে যাবে। আপনার যোগকৃত সমস্ত প্রোডাক্ট মুছে যাবে। সমস্ত বিক্রয় ইতিহাস এবং পেমেন্ট রেকর্ড হারিয়ে যাবে। বকেয়া এবং আয়ের তথ্য অ্যাক্সেসযোগ্য থাকবে না। এই ক্রিয়াটি পূর্বাবস্থায় ফেরানো যাবে না।',
  'delete_account': 'অ্যাকাউন্ট মুছুন',
  'delete_account_confirm': 'আপনি কি নিশ্চিত যে আপনার অ্যাকাউন্ট মুছতে চান?',
  'need_more_help': 'আরও সহায়তা প্রয়োজন?',
  'email_support': 'ইমেইল সাপোর্ট',
  'email_support_desc':
      'এই ইমেইলে আপনার প্রশ্ন পাঠান এবং আমাদের টিম আপনাকে দ্রুত উত্তর দেবে।',
  'user_not_logged_in': 'ব্যবহারকারী লগইন করেননি',

  // -------------------- Dashboard / Home --------------------
  'Home': 'হোম',
  'Welcome,': 'স্বাগতম,',
  'Most_Sold_Products': 'সর্বাধিক বিক্রিত পণ্য',
  'Show_Details': 'বিস্তারিত দেখুন...',
  'Sales_and_Due_Report': 'বিক্রয় ও বকেয়া রিপোর্ট',
  'Total_Product': 'মোট পণ্য',
  'Error_loading_user_data': 'ইউজার ডেটা লোড করতে ত্রুটি হয়েছে',
  'No_user_data_found': 'কোনো ইউজার ডেটা পাওয়া যায়নি',

  // -------------------- Sales --------------------
  'search_sales': 'বিক্রি অনুসন্ধান করুন (ID/গ্রাহকের নাম)',
  'sales_products': 'বিক্রিত পণ্যসমূহ',
  'sales_summary': 'বিক্রির সারসংক্ষেপ',
  'sales_history': 'বিক্রির ইতিহাস',
  'no_sales_found': 'কোন বিক্রিত পণ্যের তথ্য পাওয়া যায়নি',
  'sales': 'বিক্রয়',
  'revenue': 'আয়',
  'due': 'বাকি',
  'paid': 'পরিশোধিত',
  'filter_sales': 'বিক্রয় ফিল্টার',
  'fixed_date': 'নির্দিষ্ট তারিখ',
  'last_week': 'গত সপ্তাহ',
  'last_month': 'গত মাস',
  'last_year': 'গত বছর',
  'due_collection': 'বকেয়া সংগ্রহ',
  'product_sale': 'পণ্য বিক্রি',
  'product_sales': 'পণ্য বিক্রি',
  'product_id': 'পণ্যের আইডি',
  'quantity': 'পরিমাণ',
  'due_check': 'অনুগ্রহ করে প্রদত্ত পরিমাণ যাচাই করুন!',
  'confirm': 'নিশ্চিত করুন',
  'out_of_stock': 'স্টকে নেই, পণ্যটি আছে: ',
  'product_not_found': 'পণ্য পাওয়া যায়নি',
  'sale_saved': 'বিক্রয় সফলভাবে সংরক্ষণ করা হয়েছে!',
  'customer_name_hint': 'গ্রাহকের নাম লিখুন',
  'customer_name_label': 'গ্রাহকের নাম',
  'customer_name_required': 'গ্রাহকের নাম আবশ্যক',
  'customer_address_hint': 'গ্রাহকের ঠিকানা লিখুন',
  'customer_address_label': 'ঠিকানা',
  'customer_address_required': 'ঠিকানা আবশ্যক',

  // -------------------- Products --------------------
  'no_products_added': 'কোনো পণ্য যোগ করা হয়নি',
  'grand_total': 'মোট',
  'unit_price': 'একক মূল্য',
  'total': 'মোট',
  'Search': 'অনুসন্ধান',
  'update_sale': 'বিক্রয় হালনাগাদ',
  'check_paid_amount': 'অনুগ্রহ করে পরিশোধের পরিমাণ চেক করুন!',
  'update_sale_btn': 'বিক্রয় হালনাগাদ করুন',
  'sale_not_found': 'বিক্রয় পাওয়া যায়নি',
  'failed_fetch_sale': 'বিক্রয় ডেটা লোড করতে ব্যর্থ',
  'sale_updated_success': 'বিক্রয় সফলভাবে হালনাগাদ হয়েছে!',
  'failed_update_sale': 'বিক্রয় হালনাগাদ করতে ব্যর্থ',
  'search_product': 'পণ্য খুঁজুন',
  'no_products_found': 'কোনো পণ্য পাওয়া যায়নি',
  'products': 'পণ্যসমূহ',
  'products_found': 'পণ্য পাওয়া গেছে',
  'add_product': 'পণ্য যোগ করুন',
  'add_product_title': 'পণ্য নিবন্ধন',
  'filter': 'ফিল্টার',
  'add_product_btn': 'পণ্য যোগ করুন',
  'select_product_image': 'একটি পণ্যের ছবি নির্বাচন করুন!',
  'image_upload_failed': 'ছবি আপলোড ব্যর্থ হয়েছে!',
  'product_added_success': 'পণ্য সফলভাবে যোগ করা হয়েছে!',
  'product_id_exists': 'পণ্যের আইডি ইতিমধ্যেই আছে!',
  'error_adding_product': 'পণ্য যোগ করতে সমস্যা হয়েছে',
  'product_name_hint': 'পণ্যের নাম লিখুন',
  'product_name_label': 'পণ্যের নাম',
  'product_name_required': 'পণ্যের নাম আবশ্যক',
  'enter_product_brand': 'পণ্য ব্র্যান্ড লিখুন',
  'product_brand': 'পণ্য ব্র্যান্ড',
  'brand_name_required': 'ব্র্যান্ড নাম আবশ্যক',
  'enter_product_id': 'পণ্য আইডি লিখুন',
  'product_id_required': 'পণ্য আইডি আবশ্যক',
  'enter_purchase_price': 'ক্রয় মূল্য লিখুন',
  'purchase_price': 'ক্রয় মূল্য',
  'purchase_price_required': 'ক্রয় মূল্য আবশ্যক',
  'enter_selling_price': 'বিক্রয় মূল্য লিখুন',
  'selling_price': 'বিক্রয় মূল্য',
  'selling_price_required': 'বিক্রয় মূল্য আবশ্যক',
  'enter_discount': 'ছাড়ের পরিমাণ লিখুন',
  'discount': 'ছাড়',
  'discount_required': 'ছাড়ের পরিমাণ আবশ্যক',
  'enter_product_quantity': 'পণ্যের পরিমাণ লিখুন',
  'product_quantity': 'পণ্যের পরিমাণ',
  'product_quantity_required': 'পণ্যের পরিমাণ আবশ্যক',
  'enter_supplier_name': 'সরবরাহকারীর নাম লিখুন',
  'supplier_name': 'সরবরাহকারীর নাম',
  'supplier_name_required': 'সরবরাহকারীর নাম আবশ্যক',
  'enter_manufacture_date': 'প্রসেসের তারিখ লিখুন',
  'manufacture_date': 'উৎপাদনের তারিখ',
  'manufacture_date_required': 'প্রসেসের তারিখ আবশ্যক',
  'enter_expire_date': 'মেয়াদ শেষের তারিখ লিখুন',
  'expire_date': 'মেয়াদ শেষের তারিখ',
  'expire_date_required': 'মেয়াদ শেষের তারিখ আবশ্যক',
  'product_description_hint': 'পণ্যের বিবরণ লিখুন',
  'product_description': 'পণ্যের বিবরণ',
  'product_description_required': 'পণ্যের বিবরণ আবশ্যক',
  'select_image': 'ছবি নির্বাচন করুন',
  'gallery': 'গ্যালারি',
  'camera': 'ক্যামেরা',
  'tap_to_select_image': 'ছবি নির্বাচনের জন্য চাপুন',
  'error_picking_image': 'ছবি নেওয়ার সময় ত্রুটি',
  'error_retrieving_image': 'ছবির তথ্য পুনরুদ্ধারে ত্রুটি',
  'product_details': 'পণ্যের বিস্তারিত',
  'product_information': 'পণ্যের তথ্য',
  'brand_name': 'ব্র্যান্ডের নাম',
  'quantity_in_stock': 'স্টকে পরিমাণ',
  'product_code': 'পণ্যের কোড',
  'expiry_date': 'মেয়াদ শেষের তারিখ',
  'edit': 'সম্পাদনা',
  'delete': 'মুছে ফেলুন',
  'delete_product': 'পণ্য মুছে ফেলুন',
  'delete_confirmation': 'আপনি কি নিশ্চিত যে আপনি এই পণ্যটি মুছে ফেলতে চান?',
  'product_deleted_success': 'পণ্য সফলভাবে মুছে ফেলা হয়েছে',
  'delete_failed': 'মুছে ফেলতে ব্যর্থ',
  'update_product': 'হালনাগাদ পণ্য',
  'update_product_btn': 'পণ্য হালনাগাদ করুন',
  'cancelText_bn': 'বাতিল করুন',
  'filter_products': 'পণ্য ফিল্টার করুন',
  'all_products': 'সব পণ্য',
  'low_stock': 'স্টক কম',
  'expired': 'মেয়াদ শেষ',
  'expire_soon': 'শীঘ্রই মেয়াদ শেষ',
  'a_to_z': 'A → Z',
  'z_to_a': 'Z → A',

  // -------------------- Drawer / Misc --------------------
  'Edit_Profile': 'প্রোফাইল সম্পাদনা',
  'Are_you_sure_you_want_to_logout?': 'আপনি কি নিশ্চিত লগআউট করতে চান?',
};
