Map<String, String> English = {
  // -------------------- App Info --------------------
  //'Version': 'Version',
  'version': 'version',
  'App_Version': 'App Version',

  // --------------------  Login --------------------
  'Login_Headline': 'Welcome To Bikretaa',
  'Sign_in_bottom_text_1': "Don't have an account? ",
  'Sign_in_bottom_text_2': 'Sign Up',
  'Forgot_password': 'Forgot Password',
  'Please_enter_email_address_to_reset_the_password':
      'Please enter email address to reset the password',
  'Login_Button': 'Login',
  'BackTo_login': 'Back to login',
  'Please_enter_an_email_address': 'Please enter an email address',
  'Please_enter_a_valid_email_address': 'Please enter a valid email address',
  'Please_enter_Password': 'Please enter Password',
  'Password_hints':
      'Password must be 8+ chars with uppercase, lowercase & special char',
  'No_account_found': 'No account found',
  'Login_successful!': 'Login successful!',
  'user_not_found': 'user not found',
  'No_account_found_for_that_email': 'No account found for that email.',
  'wrong_password': 'wrong-password',
  'Incorrect_password_Please_try_again.':
      'Incorrect password. Please try again.',
  'invalid_email.': 'invalid-email',
  'The_email_address_is_not_valid..': 'The email address is not valid.',
  'Login_failed_Please_try_again': 'Login failed. Please try again.',
  'Password_Reset_Link_sent_successfully_Check_your_email':
      'Password Reset Link sent successfully! Check your email',
  'Too_many_requests_Please_try_again_later.':
      'Too many requests. Please try again later.',
  'Account_already_exists_with_this_email':
      'Account already exists with this email.',

  // -------------------- SignUp --------------------
  'SignUp_Headline': 'Create Account',
  'SignUp_subHeadLine': "We'll send to one-time password to your email address",
  'Sign_up_bottom_text_1': 'Have an account? ',
  'Sign_up_bottom_text_2': ' Sign In',
  'SignUp_Button': 'Sign Up',
  'Shop_HeadLine': 'Shop Information',
  'Email': 'Email',
  'Password': 'Password',
  'Confirm_Password': 'Confirm Password',
  'First_Name': 'First Name',
  'Last_Name': 'Last Name',
  'Phone_Number': 'Phone Number',
  'Shop_Name': 'Shop Name',
  'Address': 'Address',
  'Select_shop_type': 'Select Shop Type',
  'Shop_name_is_required': 'Shop name is required',
  'Please_enter_phone_number': 'Please enter phone number',
  'Please_enter_a_valid_phone_number': 'Please enter a valid phone number',
  'Please_select_shop_type': 'Please select shop type',
  'Passwords_do_not_match': 'Passwords do not match',
  'Sign_Up_Successful': 'Sign Up Successful!',
  'Your_password_is_too_weak_Please_use_at.....':
      'Your password is too weak. Please use at least 6 characters.',
  'This_email_is_already_registered':
      'This email is already registered. Try signing in.',
  'Something_went_wrong': 'Something went wrong. Please try again.',

  // -------------------- OTP --------------------
  'OTP_Headline': 'OTP Verification',
  'OTP_subHeadLine': 'Enter verification code sent to your email address',
  'Didnt_receive_a_code': "Didn't receive a code?",
  'Resend': 'Resend',
  'OTP_Button': 'Verify',
  'OTP_Verified_Successfully': 'OTP Verified Successfully',
  'Invalid_OTP_Please_try_again': 'Invalid OTP! Please try again',

  // -------------------- Settings --------------------
  'Settings': 'Settings',
  'Account': 'Account',
  'Profile': 'Profile',
  'Name_phone_address': 'Name, phone, address',
  'Notifications': 'Notifications',
  'Push_Notifications': 'Push Notifications',
  'Enable_all_notifications': 'Enable all notifications',
  'Expire_date_Alerts': 'Expire date Alerts',
  'Get_notified_before_items_expire': 'Get notified before items expire',
  'Low_Stock_Alerts': 'Low Stock Alerts',
  'Get_notified_when_stock_is_low': 'Get notified when stock is low',
  'Security': 'Security',
  'Change_Password': 'Change Password',
  'Update_your_account_password': 'Update your account password',
  'Language_Theme': 'Language & Theme',
  'Language': 'Language',
  'Theme': 'Theme',
  'Dark_mode_is_active': 'Dark mode is active',
  'Light_mode_is_active': 'Light mode is active',
  'About_Help': 'About & Help',
  'Support_FAQs': 'Support & FAQs',
  'Get_help_or_contact_support': 'Get help or contact support',
  'About_Us': 'About Us',
  'Learn_more_about_Bikretaa': 'Learn more about Bikretaa',
  'DANGER_ZONE': 'Account Controls',
  'Log_out': 'Log out',
  'Logout': 'Logout',
  'Reset_Password': 'Reset Password',
  'Send': 'Send',
  'Are_you_sure_you_want_to_Logout': 'Are you sure you want to Logout?',
  'Reset_Password_Message': 'Do you want to send a password reset link to',
  'Password_Reset_Success': 'Password reset link sent to',

  // -------------------- Profile --------------------
  'update_profile': 'Update Profile',
  'update_profile_btn': 'Update',
  'user_data_not_found': 'Error: User data not found',
  'profile_updated_success': 'Profile updated successfully!',
  'error_updating_profile': 'Error updating profile',
  'profile': 'Profile',
  'error_loading_user': 'Error loading user data',
  'no_user_data': 'No user data found',
  'contact_information': 'Contact Information',
  'edit_profile': 'Edit Profile',
  'change_password': 'Change Password',

  // -------------------- About Bikretaa --------------------
  'about_bikretaa': 'About Bikretaa',
  'bikretaa_description':
      'Bikretaa is a modern shop management app. It is designed specifically for shop owners to easily add products, track stock and expiry dates, manage due payments, and view detailed sales reports in one place.',
  'why_bikretaa': 'Why Bikretaa?',
  'fast_product_management': 'Fast product management',
  'stock_and_expiry_tracking': 'Stock and expiry date tracking',
  'low_stock_alerts': 'Low stock & expiry alerts',
  'sales_reports': 'Sales reports & analytics',
  'secure_login': 'Secure login & account management',
  'developed_by': 'Developed by:',
  'footer_text': '© 2025 Bikretaa Team. All Rights Reserved.',

  // -------------------- FAQs / Support --------------------
  'support_faqs': 'Support & FAQs',
  'support_welcome':
      "Welcome to Bikretaa Support! Here you'll find answers to frequently asked questions and guides on using the app.",
  'faq_manage_products_title': 'How to manage products?',
  'faq_manage_products_desc':
      "Go to the Product screen and tap on 'Add Product' to enter new items. You can set purchase price, selling price, stock quantity, expiry date, and discount. All added products will be visible in the product screen.",
  'faq_track_sales_title': 'How to track sales?',
  'faq_track_sales_desc':
      "Every sale is automatically recorded in the sales section. You can view daily, weekly, and monthly reports with graphical charts for better analysis.",
  'faq_stock_alerts_title': 'How to manage low stock and expiry alerts?',
  'faq_stock_alerts_desc':
      "Enable notifications from the Settings page. The app will alert you whenever stock is low or products are near expiry.",
  'faq_reset_password_title': 'How to reset password?',
  'faq_reset_password_desc':
      "Go to Settings > Security > Change Password. A password reset link will be sent to your registered email.",

  // -------------------- Account Deletion --------------------
  'account_deletion': 'Account Deletion',
  'account_deletion_warning':
      'Deleting your account will have the following consequences:',
  'account_deletion_desc':
      'Your personal account information will be permanently removed. All products you added will be deleted. All sales history and payment records will be lost. Due amounts and revenue data will no longer be accessible. This action cannot be undone.',
  'delete_account': 'Delete Account',
  'delete_account_confirm': 'Are you sure you want to delete your account?',
  'need_more_help': 'Need More Help?',
  'email_support': 'Email Support',
  'email_support_desc':
      'Send your queries to this email and our team will respond to you promptly.',
  'user_not_logged_in': 'User not logged in',

  // -------------------- Dashboard / Home --------------------
  'Home': 'Home',
  'Welcome,': 'Welcome,',
  'Most_Sold_Products': 'Most Sold Products',
  'Show_Details': 'Show Details...',
  'Sales_and_Due_Report': 'Sales and Due Report',
  'Total_Product': 'Total Product',
  'Error_loading_user_data': 'Error loading user data',
  'No_user_data_found': 'No user data found',

  // -------------------- Sales --------------------
  'search_sales': 'Search sales (ID/Customer name)',
  'sales_products': 'Sales Products',
  'sales_summary': 'Sales Summary',
  'sales_history': 'Sales History',
  'no_sales_found': 'No sold product information found',
  'sales': 'Sales',
  'revenue': 'Revenue',
  'due': 'Due',
  'paid': 'Paid',
  'filter_sales': 'Filter Sales',
  'fixed_date': 'Fixed Date',
  'last_week': 'Last Week',
  'last_month': 'Last Month',
  'last_year': 'Last Year',
  'due_collection': 'Due Collection',
  'product_sale': 'Product Sale',
  'product_sales': 'Product Sale',
  'product_id': 'Product ID',
  'quantity': 'Quantity',
  'due_check': 'Please check your paid amount!',
  'confirm': 'Confirm',
  'out_of_stock': 'Out of stock! Only available : ',
  'product_not_found': 'Product not found',
  'sale_saved': 'Sale saved successfully!',
  'customer_name_hint': 'Enter customer name',
  'customer_name_label': 'Customer Name',
  'customer_name_required': 'Customer Name is required',
  'customer_address_hint': 'Enter customer address',
  'customer_address_label': 'Address',
  'customer_address_required': 'Address is required',

  // -------------------- Products --------------------
  'no_products_added': 'No products added',
  'grand_total': 'Grand Total',
  'unit_price': 'Unit',
  'total': 'Total',
  'Search': 'Search',
  'update_sale': 'Update Sale',
  'check_paid_amount': 'Please check your paid amount!',
  'update_sale_btn': 'Update Sale',
  'sale_not_found': 'Sale not found',
  'failed_fetch_sale': 'Failed to fetch sale',
  'sale_updated_success': 'Sale updated successfully!',
  'failed_update_sale': 'Failed to update sale',
  'search_product': 'Search product',
  'no_products_found': 'No products found',
  'products': 'Products',
  'products_found': 'products found',
  'add_product': 'Add Product',
  'add_product_title': 'Add Product',
  'filter': 'Filter',
  'add_product_btn': 'Add Product',
  'select_product_image': 'Please select a product image!',
  'image_upload_failed': 'Image upload failed!',
  'product_added_success': 'Product added successfully!',
  'product_id_exists': 'Product ID already exists!',
  'error_adding_product': 'Error adding product',
  'product_name_hint': 'Enter product name',
  'product_name_label': 'Product Name',
  'product_name_required': 'Product Name is required',
  'enter_product_brand': 'Enter product brand',
  'product_brand': 'Product Brand',
  'brand_name_required': 'Brand name is required',
  'enter_product_id': 'Enter product id',
  'product_id_required': 'Product id is required',
  'enter_purchase_price': 'Enter purchase price',
  'purchase_price': 'Purchase Price',
  'purchase_price_required': 'Purchase Price is required',
  'enter_selling_price': 'Enter selling price',
  'selling_price': 'Selling Price',
  'selling_price_required': 'Selling Price is required',
  'enter_discount': 'Enter discount amount',
  'discount': 'Discount',
  'discount_required': 'Discount is required',
  'enter_product_quantity': 'Enter product quantity',
  'product_quantity': 'Product Quantity',
  'product_quantity_required': 'Product Quantity is required',
  'enter_supplier_name': 'Enter supplier name',
  'supplier_name': 'Supplier Name',
  'supplier_name_required': 'Supplier name is required',
  'enter_manufacture_date': 'Enter manufacture date',
  'manufacture_date': 'Manufacture Date',
  'manufacture_date_required': 'Manufacture date is required',
  'enter_expire_date': 'Enter expire date',
  'expire_date': 'Expire Date',
  'expire_date_required': 'Expire date is required',
  'product_description_hint': 'Enter product description',
  'product_description': 'Product Description',
  'product_description_required': 'Product Description is required',
  'select_image': 'Select Image',
  'gallery': 'Gallery',
  'camera': 'Camera',
  'tap_to_select_image': 'Tap to select image',
  'error_picking_image': 'Error picking image',
  'error_retrieving_image': 'Error retrieving lost image data',
  'product_details': 'Product Details',
  'product_information': 'Product Information',
  'brand_name': 'Brand Name',
  'quantity_in_stock': 'Quantity in Stock',
  'product_code': 'Product Code',
  'expiry_date': 'Expiry Date',
  'edit': 'Edit',
  'delete': 'Delete',
  'delete_product': 'Delete Product',
  'delete_confirmation': 'Are you sure you want to delete this product?',
  'product_deleted_success': 'Product deleted successfully',
  'delete_failed': 'Failed to delete',
  'update_product': 'Update Product',
  'update_product_btn': 'Update Product',
  'cancelText_bn': 'Cancel',
  'filter_products': 'Filter Products',
  'all_products': 'All Products',
  'low_stock': 'Low Stock',
  'expired': 'Expired',
  'expire_soon': 'Expire Soon',
  'a_to_z': 'A → Z',
  'z_to_a': 'Z → A',

  // -------------------- Drawer / Misc --------------------
  'Edit_Profile': 'Edit Profile',
  'Are_you_sure_you_want_to_logout?': 'Are you sure you want to logout?',
};
